MapDiffBot: AspNetCore.Views_DmeConfiguration_Index Class Reference
AspNetCore.Views_DmeConfiguration_Index Class Reference
Public Member Functions
async override global::System.Threading.Tasks.Task ExecuteAsync ()
Properties
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager [get]
global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider [get, private set]
global::Microsoft.AspNetCore.Mvc.IUrlHelper Url [get, private set]
global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component [get, private set]
global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json [get, private set]
global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper< dynamic > Html [get, private set]
Private Attributes
string __tagHelperStringValueBuffer
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner()
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null
global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper
global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper
Static Private Attributes
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "DmeConfiguration", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Edit", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("method", "post", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
Detailed Description
Definition at line 23 of file Index.g.cshtml.cs.
Member Function Documentation
async override global.System.Threading.Tasks.Task AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync ()
Definition at line 49 of file Index.g.cshtml.cs.
References AspNetCore.Views_DmeConfiguration_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper, AspNetCore.Views_DmeConfiguration_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper, AspNetCore.Views_DmeConfiguration_Index.__tagHelperAttribute_0, AspNetCore.Views_DmeConfiguration_Index.__tagHelperAttribute_1, AspNetCore.Views_DmeConfiguration_Index.__tagHelperAttribute_2, AspNetCore.Views_DmeConfiguration_Index.__tagHelperExecutionContext, AspNetCore.Views_DmeConfiguration_Index.__tagHelperRunner, and AspNetCore.Views_DmeConfiguration_Index.__tagHelperScopeManager.
         {
             BeginContext(0, 23, true);
             WriteLiteral("<div class=\"row\">\r\n    ");
             EndContext();
             BeginContext(23, 394, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "a862225f33c843428a6e8e7d5a21eb1a", async() => {
                 BeginContext(95, 14, true);
                 WriteLiteral("\r\n        <h3>");
                 EndContext();
                 BeginContext(110, 18, false);
 #line 3 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
        Write(ViewBag.EditHeader);
 #line default
 #line hidden
                 EndContext();
                 BeginContext(128, 52, true);
                 WriteLiteral(":</h3>\r\n        <input type=\"text\" name=\"newDmePath\"");
                 EndContext();
                 BeginWriteAttribute("placeholder", " placeholder=\"", 180, "\"", 210, 1);
 #line 4 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
 WriteAttributeValue("", 194, ViewBag.AutoDme, 194, 16, false);
 #line default
 #line hidden
                 EndWriteAttribute();
                 BeginWriteAttribute("value", " value=\"", 211, "\"", 237, 1);
 #line 4 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
 WriteAttributeValue("", 219, ViewBag.TargetDme, 219, 18, false);
 #line default
 #line hidden
                 EndWriteAttribute();
                 BeginContext(238, 59, true);
                 WriteLiteral(" />\r\n        <button type=\"submit\" class=\"btn btn-primary\" ");
                 EndContext();
                 BeginContext(299, 79, false);
 #line 5 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
                                                   Write(ViewBag.AuthLevel == AuthenticationLevel.Maintainer ? String.Empty : "disabled");
 #line default
 #line hidden
                 EndContext();
                 BeginContext(379, 1, true);
                 WriteLiteral(">");
                 EndContext();
                 BeginContext(381, 14, false);
 #line 5 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
                                                                                                                                     Write(ViewBag.Submit);
 #line default
 #line hidden
                 EndContext();
                 BeginContext(395, 15, true);
                 WriteLiteral("</button>\r\n    ");
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
             __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Action = (string)__tagHelperAttribute_1.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
             __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Method = (string)__tagHelperAttribute_2.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(417, 2, true);
             WriteLiteral("\r\n");
             EndContext();
 #line 7 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
      if (ViewBag.AuthLevel != AuthenticationLevel.Maintainer)
     {
 #line default
 #line hidden
             BeginContext(489, 42, true);
             WriteLiteral("        <span class=\"label label-warning\">");
             EndContext();
             BeginContext(532, 17, false);
 #line 9 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
                                      Write(ViewBag.OnlyMemes);
 #line default
 #line hidden
             EndContext();
             BeginContext(549, 9, true);
             WriteLiteral("</span>\r\n");
             EndContext();
 #line 10 "C:\projects\mapdiffbot\MapDiffBot\Views\DmeConfiguration\Index.cshtml"
     }
 #line default
 #line hidden
             BeginContext(565, 6, true);
             WriteLiteral("</div>");
             EndContext();
         }
Member Data Documentation
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager AspNetCore.Views_DmeConfiguration_Index.__backed__tagHelperScopeManager = null private
Definition at line 34 of file Index.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper AspNetCore.Views_DmeConfiguration_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper private
Definition at line 46 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
global.Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper AspNetCore.Views_DmeConfiguration_Index.__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper private
Definition at line 47 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_DmeConfiguration_Index.__tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "DmeConfiguration", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 25 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_DmeConfiguration_Index.__tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Edit", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 26 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_DmeConfiguration_Index.__tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("method", "post", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 27 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext AspNetCore.Views_DmeConfiguration_Index.__tagHelperExecutionContext private
Definition at line 32 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner AspNetCore.Views_DmeConfiguration_Index.__tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner() private
Definition at line 33 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
string AspNetCore.Views_DmeConfiguration_Index.__tagHelperStringValueBuffer private
Definition at line 30 of file Index.g.cshtml.cs.
Property Documentation
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager AspNetCore.Views_DmeConfiguration_Index.__tagHelperScopeManager get private
Definition at line 36 of file Index.g.cshtml.cs.
Referenced by AspNetCore.Views_DmeConfiguration_Index.ExecuteAsync().
global.Microsoft.AspNetCore.Mvc.IViewComponentHelper AspNetCore.Views_DmeConfiguration_Index.Component get private set
Definition at line 163 of file Index.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> AspNetCore.Views_DmeConfiguration_Index.Html get private set
Definition at line 167 of file Index.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper AspNetCore.Views_DmeConfiguration_Index.Json get private set
Definition at line 165 of file Index.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider AspNetCore.Views_DmeConfiguration_Index.ModelExpressionProvider get private set
Definition at line 159 of file Index.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.IUrlHelper AspNetCore.Views_DmeConfiguration_Index.Url get private set
Definition at line 161 of file Index.g.cshtml.cs.
The documentation for this class was generated from the following file:
MapDiffBot/obj/Debug/netcoreapp2.1/Razor/Views/DmeConfiguration/Index.g.cshtml.cs