MapDiffBot: AspNetCore.Views_Shared__Layout Class Reference
AspNetCore.Views_Shared__Layout Class Reference
Public Member Functions
async override global::System.Threading.Tasks.Task ExecuteAsync ()
Properties
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager [get]
global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider [get, private set]
global::Microsoft.AspNetCore.Mvc.IUrlHelper Url [get, private set]
global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component [get, private set]
global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json [get, private set]
global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper< dynamic > Html [get, private set]
Private Attributes
string __tagHelperStringValueBuffer
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner()
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null
global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper
global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper
global::Microsoft.AspNetCore.Mvc.TagHelpers.ScriptTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper
Static Private Attributes
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", "https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-fallback-test", "window.jQuery", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("crossorigin", new global::Microsoft.AspNetCore.Html.HtmlString("anonymous"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("integrity", new global::Microsoft.AspNetCore.Html.HtmlString("sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", "https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-fallback-test", "window.jQuery && window.jQuery.fn && window.jQuery.fn.modal", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("integrity", new global::Microsoft.AspNetCore.Html.HtmlString("sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
Detailed Description
Definition at line 23 of file _Layout.g.cshtml.cs.
Member Function Documentation
async override global.System.Threading.Tasks.Task AspNetCore.Views_Shared__Layout.ExecuteAsync ()
Definition at line 54 of file _Layout.g.cshtml.cs.
References AspNetCore.Views_Shared__Layout.__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper, AspNetCore.Views_Shared__Layout.__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper, AspNetCore.Views_Shared__Layout.__Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_0, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_1, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_2, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_3, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_4, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_5, AspNetCore.Views_Shared__Layout.__tagHelperAttribute_6, AspNetCore.Views_Shared__Layout.__tagHelperExecutionContext, AspNetCore.Views_Shared__Layout.__tagHelperRunner, and AspNetCore.Views_Shared__Layout.__tagHelperScopeManager.
         {
             BeginContext(0, 25, true);
             WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n");
             EndContext();
             BeginContext(25, 980, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "01f3799a353d418781ade3027fc51b85", async() => {
                 BeginContext(31, 121, true);
                 WriteLiteral("\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n    <title>");
                 EndContext();
                 BeginContext(153, 13, false);
 #line 6 "C:\projects\mapdiffbot\MapDiffBot\Views\Shared\_Layout.cshtml"
       Write(ViewBag.Title);
 #line default
 #line hidden
                 EndContext();
                 BeginContext(166, 832, true);
                 WriteLiteral(@"</title>
     <link rel=""stylesheet"" href=""https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"" />
     <link rel=""stylesheet"" href=""https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"">
     <link rel=""apple-touch-icon"" sizes=""180x180"" href=""/apple-touch-icon.png"">
     <link rel=""icon"" type=""image/png"" sizes=""32x32"" href=""/favicon-32x32.png"">
     <link rel=""icon"" type=""image/png"" sizes=""16x16"" href=""/favicon-16x16.png"">
     <link rel=""manifest"" href=""/site.webmanifest"">
     <link rel=""mask-icon"" href=""/safari-pinned-tab.svg"" color=""#5bbad5"">
     <meta name=""msapplication-TileColor"" content=""#da532c"">
     <meta name=""theme-color"" content=""#ffffff"">
     <link href=""https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css"" rel=""stylesheet"">
 ");
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(1005, 2, true);
             WriteLiteral("\r\n");
             EndContext();
             BeginContext(1007, 1389, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "309e95dfd4934a679b1b9e9254dcabb1", async() => {
                 BeginContext(1013, 6, true);
                 WriteLiteral("\r\n    ");
                 EndContext();
                 BeginContext(1019, 269, false);
                 __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "2bde9405496546adb03b49c120fdb909", async() => {
                     BeginContext(1273, 6, true);
                     WriteLiteral("\r\n    ");
                     EndContext();
                 }
                 );
                 __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.ScriptTagHelper>();
                 __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper);
                 __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper.Src = (string)__tagHelperAttribute_0.Value;
                 __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
                 __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper.FallbackTestExpression = (string)__tagHelperAttribute_1.Value;
                 __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
                 __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                 __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                 await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                 if (!__tagHelperExecutionContext.Output.IsContentModified)
                 {
                     await __tagHelperExecutionContext.SetOutputContentAsync();
                 }
                 Write(__tagHelperExecutionContext.Output);
                 __tagHelperExecutionContext = __tagHelperScopeManager.End();
                 EndContext();
                 BeginContext(1288, 6, true);
                 WriteLiteral("\r\n    ");
                 EndContext();
                 BeginContext(1294, 321, false);
                 __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "9e9ca3cb72014490b167ae04242623e6", async() => {
                     BeginContext(1600, 6, true);
                     WriteLiteral("\r\n    ");
                     EndContext();
                 }
                 );
                 __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.ScriptTagHelper>();
                 __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper);
                 __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper.Src = (string)__tagHelperAttribute_4.Value;
                 __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
                 __Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper.FallbackTestExpression = (string)__tagHelperAttribute_5.Value;
                 __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_5);
                 __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                 __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_6);
                 await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                 if (!__tagHelperExecutionContext.Output.IsContentModified)
                 {
                     await __tagHelperExecutionContext.SetOutputContentAsync();
                 }
                 Write(__tagHelperExecutionContext.Output);
                 __tagHelperExecutionContext = __tagHelperScopeManager.End();
                 EndContext();
                 BeginContext(1615, 323, true);
                 WriteLiteral(@"
     <script src=""https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js""></script>
     <nav class=""navbar navbar-inverse navbar-fixed-top"">
         <div class=""container"">
             <div class=""navbar-header"">
                 <a class=""navbar-brand"" href=""#"">MapDiffBot</a>
             </div>
 ");
                 EndContext();
 #line 38 "C:\projects\mapdiffbot\MapDiffBot\Views\Shared\_Layout.cshtml"
              if (!ViewBag.HideLogin)
             {
 #line default
 #line hidden
                 BeginContext(1991, 134, true);
                 WriteLiteral("            <div class=\"navbar-collapse collapse\">\r\n                <ul class=\"nav navbar-nav pull-right\">\r\n                    <li><a");
                 EndContext();
                 BeginWriteAttribute("href", " href=\"", 2125, "\"", 2151, 1);
 #line 42 "C:\projects\mapdiffbot\MapDiffBot\Views\Shared\_Layout.cshtml"
 WriteAttributeValue("", 2132, ViewBag.SignInHref, 2132, 19, false);
 #line default
 #line hidden
                 EndWriteAttribute();
                 BeginContext(2152, 1, true);
                 WriteLiteral(">");
                 EndContext();
                 BeginContext(2154, 14, false);
 #line 42 "C:\projects\mapdiffbot\MapDiffBot\Views\Shared\_Layout.cshtml"
                                                  Write(ViewBag.SignIn);
 #line default
 #line hidden
                 EndContext();
                 BeginContext(2168, 54, true);
                 WriteLiteral("</a></li>\r\n                </ul>\r\n            </div>\r\n");
                 EndContext();
 #line 45 "C:\projects\mapdiffbot\MapDiffBot\Views\Shared\_Layout.cshtml"
             }
 #line default
 #line hidden
                 BeginContext(2237, 125, true);
                 WriteLiteral("        </div>\r\n    </nav>\r\n    <div class=\"container body-content\" style=\"padding-top: 70px;margin-bottom: 90px;\">\r\n        ");
                 EndContext();
                 BeginContext(2363, 12, false);
 #line 49 "C:\projects\mapdiffbot\MapDiffBot\Views\Shared\_Layout.cshtml"
    Write(RenderBody());
 #line default
 #line hidden
                 EndContext();
                 BeginContext(2375, 14, true);
                 WriteLiteral("\r\n    </div>\r\n");
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(2396, 11, true);
             WriteLiteral("\r\n</html>\r\n");
             EndContext();
         }
Member Data Documentation
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager AspNetCore.Views_Shared__Layout.__backed__tagHelperScopeManager = null private
Definition at line 38 of file _Layout.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper AspNetCore.Views_Shared__Layout.__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper private
Definition at line 51 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
global.Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper AspNetCore.Views_Shared__Layout.__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper private
Definition at line 50 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
global.Microsoft.AspNetCore.Mvc.TagHelpers.ScriptTagHelper AspNetCore.Views_Shared__Layout.__Microsoft_AspNetCore_Mvc_TagHelpers_ScriptTagHelper private
Definition at line 52 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", "https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 25 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-fallback-test", "window.jQuery", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 26 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("crossorigin", new global::Microsoft.AspNetCore.Html.HtmlString("anonymous"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 27 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("integrity", new global::Microsoft.AspNetCore.Html.HtmlString("sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 28 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", "https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 29 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-fallback-test", "window.jQuery && window.jQuery.fn && window.jQuery.fn.modal", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 30 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Shared__Layout.__tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("integrity", new global::Microsoft.AspNetCore.Html.HtmlString("sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 31 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext AspNetCore.Views_Shared__Layout.__tagHelperExecutionContext private
Definition at line 36 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner AspNetCore.Views_Shared__Layout.__tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner() private
Definition at line 37 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
string AspNetCore.Views_Shared__Layout.__tagHelperStringValueBuffer private
Definition at line 34 of file _Layout.g.cshtml.cs.
Property Documentation
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager AspNetCore.Views_Shared__Layout.__tagHelperScopeManager get private
Definition at line 40 of file _Layout.g.cshtml.cs.
Referenced by AspNetCore.Views_Shared__Layout.ExecuteAsync().
global.Microsoft.AspNetCore.Mvc.IViewComponentHelper AspNetCore.Views_Shared__Layout.Component get private set
Definition at line 236 of file _Layout.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> AspNetCore.Views_Shared__Layout.Html get private set
Definition at line 240 of file _Layout.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper AspNetCore.Views_Shared__Layout.Json get private set
Definition at line 238 of file _Layout.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider AspNetCore.Views_Shared__Layout.ModelExpressionProvider get private set
Initial value:
</title>
    <link rel=""stylesheet"" href=""https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"" />
    <link rel=""stylesheet"" href=""https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"">
    <link rel=""apple-touch-icon"" sizes=""180x180"" href=""/apple-touch-icon.png"">
    <link rel=""icon"" type=""image/png"" sizes=""32x32"" href=""/favicon-32x32.png"">
    <link rel=""icon"" type=""image/png"" sizes=""16x16"" href=""/favicon-16x16.png"">
    <link rel=""manifest"" href=""/site.webmanifest"">
    <link rel=""mask-icon"" href=""/safari-pinned-tab.svg"" color=""#5bbad5"">
    <meta name=""msapplication-TileColor"" content=""#da532c"">
    <meta name=""theme-color"" content=""#ffffff"">
    <link href=""https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css"" rel=""stylesheet"">
"
    <script src=""https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js""></script>
    <nav class=""navbar navbar-inverse navbar-fixed-top"">
        <div class=""container"">
            <div class=""navbar-header"">
                <a class=""navbar-brand"" href=""#"">MapDiffBot</a>
            </div>
"
Definition at line 232 of file _Layout.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.IUrlHelper AspNetCore.Views_Shared__Layout.Url get private set
Definition at line 234 of file _Layout.g.cshtml.cs.
The documentation for this class was generated from the following file:
MapDiffBot/obj/Release/netcoreapp2.1/Razor/Views/Shared/_Layout.g.cshtml.cs