MapDiffBot: AspNetCore.Views_Files_Browse Class Reference
AspNetCore.Views_Files_Browse Class Reference
Public Member Functions
async override global::System.Threading.Tasks.Task ExecuteAsync ()
Properties
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager [get]
global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider [get, private set]
global::Microsoft.AspNetCore.Mvc.IUrlHelper Url [get, private set]
global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component [get, private set]
global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json [get, private set]
global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper< dynamic > Html [get, private set]
Private Attributes
string __tagHelperStringValueBuffer
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner()
global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null
global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper
Static Private Attributes
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "DmeConfiguration", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "HandleAllLogsGet", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "HandleMapGet", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-route-beforeOrAfter", "before", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-route-beforeOrAfter", "after", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "HandleLogsGet", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes)
Detailed Description
Definition at line 23 of file Browse.g.cshtml.cs.
Member Function Documentation
async override global.System.Threading.Tasks.Task AspNetCore.Views_Files_Browse.ExecuteAsync ()
Definition at line 52 of file Browse.g.cshtml.cs.
References AspNetCore.Views_Files_Browse.__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper, AspNetCore.Views_Files_Browse.__tagHelperAttribute_0, AspNetCore.Views_Files_Browse.__tagHelperAttribute_1, AspNetCore.Views_Files_Browse.__tagHelperAttribute_2, AspNetCore.Views_Files_Browse.__tagHelperAttribute_3, AspNetCore.Views_Files_Browse.__tagHelperAttribute_4, AspNetCore.Views_Files_Browse.__tagHelperAttribute_5, AspNetCore.Views_Files_Browse.__tagHelperAttribute_6, AspNetCore.Views_Files_Browse.__tagHelperExecutionContext, AspNetCore.Views_Files_Browse.__tagHelperRunner, AspNetCore.Views_Files_Browse.__tagHelperScopeManager, and AspNetCore.Views_Files_Browse.__tagHelperStringValueBuffer.
         {
             BeginContext(0, 29, true);
             WriteLiteral("<div class=\"container\">\r\n    ");
             EndContext();
             BeginContext(29, 125, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "bb12089f60fb44acb3766bcb95ff7218", async() => {
                 BeginContext(133, 17, false);
 #line 2 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                       Write(ViewBag.Configure);
 #line default
 #line hidden
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-repositoryId", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             BeginWriteTagHelperAttribute();
 #line 2 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                         WriteLiteral(ViewBag.RepositoryId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-repositoryId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(154, 3, true);
             WriteLiteral(" | ");
             EndContext();
             BeginContext(157, 100, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d7201855b75c4004b14726cd6dc0e3ea", async() => {
                 BeginContext(238, 15, false);
 #line 2 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                Write(ViewBag.AllLogs);
 #line default
 #line hidden
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_2.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-repositoryId", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             BeginWriteTagHelperAttribute();
 #line 2 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                  WriteLiteral(ViewBag.RepositoryId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-repositoryId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(257, 53, true);
             WriteLiteral("\r\n</div>\r\n\r\n<hr />\r\n<div class=\"container\">\r\n    <h3>");
             EndContext();
             BeginContext(311, 16, false);
 #line 7 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
    Write(ViewBag.MapDiffs);
 #line default
 #line hidden
             EndContext();
             BeginContext(327, 8, true);
             WriteLiteral(":</h3>\r\n");
             EndContext();
 #line 8 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
         var counter = 0;
 #line default
 #line hidden
             BeginContext(376, 4, true);
             WriteLiteral("    ");
             EndContext();
 #line 11 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
      foreach (var I in ViewBag.Diffs)
     {
 #line default
 #line hidden
             BeginContext(422, 43, true);
             WriteLiteral("        <div class=\"row\">\r\n            <h4>");
             EndContext();
             BeginContext(466, 1, false);
 #line 14 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
            Write(I);
 #line default
 #line hidden
             EndContext();
             BeginContext(467, 20, true);
             WriteLiteral(":</h4>\r\n            ");
             EndContext();
             BeginContext(487, 199, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "6f45830373f54f748e7b26b49bcc2cad", async() => {
                 BeginContext(668, 14, false);
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                            Write(ViewBag.Before);
 #line default
 #line hidden
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_3.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-repositoryId", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                      WriteLiteral(ViewBag.RepositoryId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-repositoryId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                   WriteLiteral(ViewBag.CheckRunId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["checkRunId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-checkRunId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["checkRunId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                          WriteLiteral(counter);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["fileId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-fileId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["fileId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-beforeOrAfter", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["beforeOrAfter"] = (string)__tagHelperAttribute_4.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(686, 3, true);
             WriteLiteral(" | ");
             EndContext();
             BeginContext(689, 197, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "de6acd76abe946d39b60f0e5e009f408", async() => {
                 BeginContext(869, 13, false);
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                     Write(ViewBag.After);
 #line default
 #line hidden
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_3.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-repositoryId", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                WriteLiteral(ViewBag.RepositoryId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-repositoryId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                             WriteLiteral(ViewBag.CheckRunId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["checkRunId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-checkRunId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["checkRunId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                                                                    WriteLiteral(counter);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["fileId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-fileId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["fileId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-beforeOrAfter", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["beforeOrAfter"] = (string)__tagHelperAttribute_5.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_5);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(886, 3, true);
             WriteLiteral(" | ");
             EndContext();
             BeginContext(889, 165, false);
             __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "35140557e35d435a8a8fb5f2333f51fc", async() => {
                 BeginContext(1038, 12, false);
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Write(ViewBag.Logs);
 #line default
 #line hidden
                 EndContext();
             }
             );
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
             __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_6.Value;
             __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
             if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
             {
                 throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-repositoryId", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
             }
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         WriteLiteral(ViewBag.RepositoryId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-repositoryId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["repositoryId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      WriteLiteral(ViewBag.CheckRunId);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["checkRunId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-checkRunId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["checkRunId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             BeginWriteTagHelperAttribute();
 #line 15 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             WriteLiteral(counter);
 #line default
 #line hidden
             __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
             __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["fileId"] = __tagHelperStringValueBuffer;
             __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-fileId", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["fileId"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
             await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
             if (!__tagHelperExecutionContext.Output.IsContentModified)
             {
                 await __tagHelperExecutionContext.SetOutputContentAsync();
             }
             Write(__tagHelperExecutionContext.Output);
             __tagHelperExecutionContext = __tagHelperScopeManager.End();
             EndContext();
             BeginContext(1054, 18, true);
             WriteLiteral("\r\n        </div>\r\n");
             EndContext();
 #line 17 "C:\projects\mapdiffbot\MapDiffBot\Views\Files\Browse.cshtml"
         ++counter;
     }
 #line default
 #line hidden
             BeginContext(1099, 8, true);
             WriteLiteral("</div>\r\n");
             EndContext();
         }
Member Data Documentation
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager AspNetCore.Views_Files_Browse.__backed__tagHelperScopeManager = null private
Definition at line 38 of file Browse.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper AspNetCore.Views_Files_Browse.__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper private
Definition at line 50 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "DmeConfiguration", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 25 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 26 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "HandleAllLogsGet", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 27 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "HandleMapGet", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 28 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-route-beforeOrAfter", "before", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 29 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-route-beforeOrAfter", "after", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 30 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
readonly global.Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute AspNetCore.Views_Files_Browse.__tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "HandleLogsGet", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes) static private
Definition at line 31 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext AspNetCore.Views_Files_Browse.__tagHelperExecutionContext private
Definition at line 36 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner AspNetCore.Views_Files_Browse.__tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner() private
Definition at line 37 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
string AspNetCore.Views_Files_Browse.__tagHelperStringValueBuffer private
Definition at line 34 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
Property Documentation
global.Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager AspNetCore.Views_Files_Browse.__tagHelperScopeManager get private
Definition at line 40 of file Browse.g.cshtml.cs.
Referenced by AspNetCore.Views_Files_Browse.ExecuteAsync().
global.Microsoft.AspNetCore.Mvc.IViewComponentHelper AspNetCore.Views_Files_Browse.Component get private set
Definition at line 375 of file Browse.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> AspNetCore.Views_Files_Browse.Html get private set
Definition at line 379 of file Browse.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper AspNetCore.Views_Files_Browse.Json get private set
Definition at line 377 of file Browse.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider AspNetCore.Views_Files_Browse.ModelExpressionProvider get private set
Definition at line 371 of file Browse.g.cshtml.cs.
global.Microsoft.AspNetCore.Mvc.IUrlHelper AspNetCore.Views_Files_Browse.Url get private set
Definition at line 373 of file Browse.g.cshtml.cs.
The documentation for this class was generated from the following file:
MapDiffBot/obj/Release/netcoreapp2.1/Razor/Views/Files/Browse.g.cshtml.cs