MapDiffBot: MapDiffBot.Core.IGitHubManager Interface Reference
MapDiffBot.Core.IGitHubManager Interface Reference
Manages operations with GitHub.com
Public Member Functions
Uri GetAuthorizationURL (Uri callbackURL, string state)
Get the GitHub URL to direct a user to at the start of the Oauth flow
Task< string > CompleteAuthorization (HttpRequest request, IResponseCookies cookies, CancellationToken cancellationToken)
Complete the Oauth flow
void ExpireAuthorization (IResponseCookies cookies)
Expire an oauth cookie
Task< AuthenticationLevel > CheckAuthorization (long repositoryId, IRequestCookieCollection cookies, CancellationToken cancellationToken)
Checks some cookies for the oauth cookie
Task CreateSingletonComment (PullRequest pullRequest, string body, CancellationToken cancellationToken)
Creates a comment on a given pullRequest , or updates the first one if it has already done so
Task< PullRequest > GetPullRequest (long repositoryId, int pullRequestNumber, CancellationToken cancellationToken)
Gets a PullRequest
Task< IReadOnlyList< PullRequestFile > > GetPullRequestChangedFiles (PullRequest pullRequest, CancellationToken cancellationToken)
Get the files changed by a PullRequest
Task LoadInstallation (long repositoryId, CancellationToken cancellationToken)
Updates Models.IDatabaseContext.Installations for the given repositoryId
Task UpdateCheckRun (long repositoryId, long checkRunId, CheckRunUpdate checkRunUpdate, CancellationToken cancellationToken)
Update a CheckRun
Task< long > CreateCheckRun (long repositoryId, NewCheckRun newCheckRun, CancellationToken cancellationToken)
Create a CheckRun
Task< IReadOnlyList< CheckRun > > GetMatchingCheckRuns (long repositoryId, long checkSuiteId, CancellationToken cancellationToken)
Get CheckRuns matching a checkSuiteId
Detailed Description
Manages operations with GitHub.com
Definition at line 13 of file IGitHubManager.cs.
Member Function Documentation
Task<AuthenticationLevel> MapDiffBot.Core.IGitHubManager.CheckAuthorization (long repositoryId, IRequestCookieCollection cookies, CancellationToken cancellationToken)
Checks some cookies for the oauth cookie
Parameters
repositoryId The Repository.Id for the operation
cookies The IRequestCookieCollection to check
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the AuthenticationLevel of the user
Implemented in MapDiffBot.Core.GitHubManager.
Task<string> MapDiffBot.Core.IGitHubManager.CompleteAuthorization (HttpRequest request, IResponseCookies cookies, CancellationToken cancellationToken)
Complete the Oauth flow
Parameters
request The web request
cookies The IResponseCookies to write session information to
cancellationToken The CancellationToken for the operation
Returns
A Task resulting in the value of the state parameter of GetAuthorizationURL(Uri, string) on success, on failure
Implemented in MapDiffBot.Core.GitHubManager.
Task<long> MapDiffBot.Core.IGitHubManager.CreateCheckRun (long repositoryId, NewCheckRun newCheckRun, CancellationToken cancellationToken)
Create a CheckRun
Parameters
repositoryId The Repository.Id
newCheckRun The NewCheckRun
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in the new CheckRun.Id
Implemented in MapDiffBot.Core.GitHubManager.
Referenced by MapDiffBot.Core.PayloadProcessor.CreateUnassociatedCheck().
Task MapDiffBot.Core.IGitHubManager.CreateSingletonComment (PullRequest pullRequest, string body, CancellationToken cancellationToken)
Creates a comment on a given pullRequest , or updates the first one if it has already done so
Parameters
pullRequest The PullRequest to comment on
body The body of the comment
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.GitHubManager.
void MapDiffBot.Core.IGitHubManager.ExpireAuthorization (IResponseCookies cookies)
Expire an oauth cookie
Parameters
cookies The IResponseCookies to write session information to
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.GitHubManager.
Uri MapDiffBot.Core.IGitHubManager.GetAuthorizationURL (Uri callbackURL, string state)
Get the GitHub URL to direct a user to at the start of the Oauth flow
Parameters
callbackURL The Uri to direct users to to complete the Oauth flow
state A string to be passed into the query parameters of callbackURL when the use visits it with the code
Returns
The Uri to send the user to
Implemented in MapDiffBot.Core.GitHubManager.
Task<IReadOnlyList<CheckRun> > MapDiffBot.Core.IGitHubManager.GetMatchingCheckRuns (long repositoryId, long checkSuiteId, CancellationToken cancellationToken)
Get CheckRuns matching a checkSuiteId
Parameters
repositoryId The Repository.Id
checkSuiteId The CheckSuite.Id
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in an IEnumerable<T> of relevant CheckRuns
Implemented in MapDiffBot.Core.GitHubManager.
Referenced by MapDiffBot.Core.PayloadProcessor.ScanCheckSuite().
Task<PullRequest> MapDiffBot.Core.IGitHubManager.GetPullRequest (long repositoryId, int pullRequestNumber, CancellationToken cancellationToken)
Gets a PullRequest
Parameters
repositoryId The Repository.Id of the PullRequest.Base
pullRequestNumber The PullRequest.Number
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in a PullRequest
Implemented in MapDiffBot.Core.GitHubManager.
Referenced by MapDiffBot.Core.PayloadProcessor.ScanPullRequestImpl().
Task<IReadOnlyList<PullRequestFile> > MapDiffBot.Core.IGitHubManager.GetPullRequestChangedFiles (PullRequest pullRequest, CancellationToken cancellationToken)
Get the files changed by a PullRequest
Parameters
pullRequest The PullRequest
cancellationToken The CancellationToken for the operation
Returns
A Task<TResult> resulting in a IReadOnlyList<T> of PullRequestFiles
Implemented in MapDiffBot.Core.GitHubManager.
Task MapDiffBot.Core.IGitHubManager.LoadInstallation (long repositoryId, CancellationToken cancellationToken)
Updates Models.IDatabaseContext.Installations for the given repositoryId
Parameters
repositoryId The Repository.Id to load
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.GitHubManager.
Task MapDiffBot.Core.IGitHubManager.UpdateCheckRun (long repositoryId, long checkRunId, CheckRunUpdate checkRunUpdate, CancellationToken cancellationToken)
Update a CheckRun
Parameters
repositoryId The Repository.Id
checkRunId The CheckRun.Id
checkRunUpdate The CheckRunUpdate
cancellationToken The CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.GitHubManager.
The documentation for this interface was generated from the following file:
MapDiffBot/Core/IGitHubManager.cs