MapDiffBot: MapDiffBot.Core.IIOManager Interface Reference
MapDiffBot.Core.IIOManager Interface Reference
Interface for using filesystems
Public Member Functions
string ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this call this internally on given paths
string GetFileName (string path)
Gets the file name portion of a path
string GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with
Task< bool > FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists
Task< byte[]> ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array
Task WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content
Task CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest
Task< List< string > > GetFilesWithExtension (string path, string extension, CancellationToken cancellationToken)
Gets a list of files in path with the given extension
Task DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path
Task CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path
Task DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory
string ConcatPath (params string[] paths)
Combines an array of strings into a path
Task MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination
Detailed Description
Interface for using filesystems
Definition at line 10 of file IIOManager.cs.
Member Function Documentation
string MapDiffBot.Core.IIOManager.ConcatPath (params string[] paths)
Combines an array of strings into a path
Parameters
paths The paths to combine
Returns
The combined path
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
Task MapDiffBot.Core.IIOManager.CopyFile (string src, string dest, CancellationToken cancellationToken)
Copy a file from src to dest
Parameters
src The source file to copy
dest The destination path
cancellationToken A CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
Task MapDiffBot.Core.IIOManager.CreateDirectory (string path, CancellationToken cancellationToken)
Create a directory at path
Parameters
path The path of the directory to create
cancellationToken A CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
Task MapDiffBot.Core.IIOManager.DeleteDirectory (string path, CancellationToken cancellationToken)
Recursively delete a directory
Parameters
path The path to the directory to delete
cancellationToken A CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.Application.Configure(), and MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
Task MapDiffBot.Core.IIOManager.DeleteFile (string path, CancellationToken cancellationToken)
Deletes a file at path
Parameters
path The path of the file to delete
cancellationToken A CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
Task<bool> MapDiffBot.Core.IIOManager.FileExists (string path, CancellationToken cancellationToken)
Check that the file at path exists
Parameters
path The file to check for existence
cancellationToken The CancellationToken for the operation
Returns
A Task resulting in if the file at path exists, otherwise
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
string MapDiffBot.Core.IIOManager.GetFileName (string path)
Gets the file name portion of a path
Parameters
path The path to get the file name of
Returns
The file name portion of path
Implemented in MapDiffBot.Core.DefaultIOManager.
string MapDiffBot.Core.IIOManager.GetFileNameWithoutExtension (string path)
Gets the file name portion of a path with
Parameters
path The path to get the file name of
Returns
The file name portion of path
Implemented in MapDiffBot.Core.DefaultIOManager.
Task<List<string> > MapDiffBot.Core.IIOManager.GetFilesWithExtension (string path, string extension, CancellationToken cancellationToken)
Gets a list of files in path with the given extension
Parameters
path The directory which contains the files
extension The extension to look for without the preceeding "."
cancellationToken A CancellationToken for the operation
Returns
A Task resulting in a list of paths to files in path with the given extension
Implemented in MapDiffBot.Core.DefaultIOManager.
Task MapDiffBot.Core.IIOManager.MoveFile (string source, string destination, CancellationToken cancellationToken)
Moves a file at source to destination
Parameters
source The source file path
destination The destination path
cancellationToken A CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.DefaultIOManager.
Task<byte[]> MapDiffBot.Core.IIOManager.ReadAllBytes (string path, CancellationToken cancellationToken)
Returns all the contents of a file at path as a byte array
Parameters
path The path of the file to read
cancellationToken A CancellationToken for the operation
Returns
A Task that results in the contents of a file at path
Implemented in MapDiffBot.Core.DefaultIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs().
string MapDiffBot.Core.IIOManager.ResolvePath (string path)
Retrieve the full path of some path given a relative path. Must be used before passing relative paths to other APIs. All other operations in this call this internally on given paths
Parameters
path Some path to retrieve the full path of
Returns
path as a full canonical path
Implemented in MapDiffBot.Core.DefaultIOManager, and MapDiffBot.Core.ResolvingIOManager.
Referenced by MapDiffBot.Core.PayloadProcessor.GenerateDiffs(), and MapDiffBot.Core.ResolvingIOManager.ResolvingIOManager().
Task MapDiffBot.Core.IIOManager.WriteAllBytes (string path, byte[] contents, CancellationToken cancellationToken)
Writes some contents to a file at path overwriting previous content
Parameters
path The path of the file to write
contents The contents of the file
cancellationToken A CancellationToken for the operation
Returns
A Task representing the running operation
Implemented in MapDiffBot.Core.DefaultIOManager.
The documentation for this interface was generated from the following file:
MapDiffBot/Core/IIOManager.cs