$bf = $Env:APPVEYOR_BUILD_FOLDER

$doxdir = "C:\tgsdox"

New-Item -Path $doxdir -ItemType directory

$publish_dox = (-not (Test-Path Env:APPVEYOR_PULL_REQUEST_NUMBER)) -and ("$Env:APPVEYOR_REPO_BRANCH" -eq "master")

if($publish_dox){
	$github_url = "github.com/$Env:APPVEYOR_REPO_NAME"
	Write-Output "Cloning https://git@$github_url..."
	git clone -b gh-pages --single-branch "https://git@$github_url" "$doxdir" 2>$null
	Remove-Item -r "$doxdir\*"
	Add-Content "$bf\Tools\Doxyfile" "`nPROJECT_NUMBER = $version`nINPUT = $bf`nOUTPUT_DIRECTORY = $doxdir"
}else{
	Add-Content "$bf\Tools\Doxyfile" "`nPROJECT_NUMBER = $version`nINPUT = $bf`nOUTPUT_DIRECTORY = $doxdir"
}

Start-Process -FilePath "C:/Program Files/doxygen/bin/doxygen.exe" -ArgumentList "$bf\Tools\Doxyfile"

if($publish_dox){
	Set-Location $doxdir
	git config --global push.default simple
	git config user.name "Cyberboss"
	git config user.email "Cyberboss@users.noreply.github.com"
	Write-Output '# THIS BRANCH IS AUTO GENERATED BY APPVEYOR CI' > README.md
	
	# Need to create a .nojekyll file to allow filenames starting with an underscore
	# to be seen on the gh-pages site. Therefore creating an empty .nojekyll file.
	Write-Output "" > .nojekyll
	git add --all
	git commit -m "Deploy code docs to GitHub Pages for Appveyor build $Env:APPVEYOR_BUILD_NUMBER" -m "Commit: $Env:APPVEYOR_REPO_COMMIT"
	git push -f "https://$Env:repo_token@$github_url" 2>&1 | out-null
	$Env:repo_token = ""
	Set-Location "$bf"
}
